#ifndef EPMODEL_StraightComponent_I
#define EPMODEL_StraightComponent_I

#ifdef SWIGPYTHON
  %module openstudioepmodelstraightcomponent
#endif

%include <epmodel/EPModel_Common_Include.i>
%import <epmodel/EPModel.i>
%import <epmodel/HVACComponent/EPModelHVACComponent.i>

EPMODELOBJECT_WRAP(StraightComponent, <epmodel/StraightComponent/StraightComponent.hpp>, 0, 0)
EPMODELOBJECT_WRAP(AirConditionerVariableRefrigerantFlow, <epmodel/StraightComponent/AirConditionerVariableRefrigerantFlow.hpp>, 0, 1)
EPMODELOBJECT_WRAP(SolarCollectorFlatPlatePhotovoltaicThermal, <epmodel/StraightComponent/SolarCollectorFlatPlatePhotovoltaicThermal.hpp>, 0, 1)
EPMODELOBJECT_WRAP(SolarCollectorFlatPlateWater, <epmodel/StraightComponent/SolarCollectorFlatPlateWater.hpp>, 0, 1)
EPMODELOBJECT_WRAP(SolarCollectorIntegralCollectorStorage, <epmodel/StraightComponent/SolarCollectorIntegralCollectorStorage.hpp>, 0, 1)
EPMODELOBJECT_WRAP(HeatPumpAirToWater, <epmodel/StraightComponent/HeatPumpAirToWater.hpp>, 0, 1)
EPMODELOBJECT_WRAP(HeatPumpAirToWaterFuelFiredCooling, <epmodel/StraightComponent/HeatPumpAirToWaterFuelFiredCooling.hpp>, 0, 1)
EPMODELOBJECT_WRAP(HeatPumpAirToWaterFuelFiredHeating, <epmodel/StraightComponent/HeatPumpAirToWaterFuelFiredHeating.hpp>, 0, 1)
EPMODELOBJECT_WRAP(LoadProfilePlant, <epmodel/StraightComponent/LoadProfilePlant.hpp>, 0, 1)
EPMODELOBJECT_WRAP(PlantComponentTemperatureSource, <epmodel/StraightComponent/PlantComponentTemperatureSource.hpp>, 0, 1)
EPMODELOBJECT_WRAP(PlantComponentUserDefined, <epmodel/StraightComponent/PlantComponentUserDefined.hpp>, 0, 1)
EPMODELOBJECT_WRAP(SwimmingPoolIndoor, <epmodel/StraightComponent/SwimmingPoolIndoor.hpp>, 0, 1)
EPMODELOBJECT_WRAP(TemperingValve, <epmodel/StraightComponent/TemperingValve.hpp>, 0, 1)
EPMODELOBJECT_WRAP(WaterUseConnections, <epmodel/StraightComponent/WaterUseConnections.hpp>, 0, 1)
EPMODELOBJECT_WRAP(ThermalStorageIceDetailed, <epmodel/StraightComponent/ThermalStorageIceDetailed.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoilCoolingDXVariableRefrigerantFlow, <epmodel/StraightComponent/CoilCoolingDXVariableRefrigerantFlow.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoilCoolingDXVariableRefrigerantFlowFluidTemperatureControl, <epmodel/StraightComponent/CoilCoolingDXVariableRefrigerantFlowFluidTemperatureControl.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoilHeatingDXVariableRefrigerantFlow, <epmodel/StraightComponent/CoilHeatingDXVariableRefrigerantFlow.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoilHeatingWaterBaseboard, <epmodel/StraightComponent/CoilHeatingWaterBaseboard.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoilHeatingLowTempRadiantConstFlow, <epmodel/StraightComponent/CoilHeatingLowTempRadiantConstFlow.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoilHeatingWaterBaseboardRadiant, <epmodel/StraightComponent/CoilHeatingWaterBaseboardRadiant.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoilHeatingLowTempRadiantVarFlow, <epmodel/StraightComponent/CoilHeatingLowTempRadiantVarFlow.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoilHeatingDXVariableRefrigerantFlowFluidTemperatureControl, <epmodel/StraightComponent/CoilHeatingDXVariableRefrigerantFlowFluidTemperatureControl.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoilCoolingLowTempRadiantConstFlow, <epmodel/StraightComponent/CoilCoolingLowTempRadiantConstFlow.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoilCoolingLowTempRadiantVarFlow, <epmodel/StraightComponent/CoilCoolingLowTempRadiantVarFlow.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoilCoolingWaterPanelRadiant, <epmodel/StraightComponent/CoilCoolingWaterPanelRadiant.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoilWaterHeatingAirToWaterHeatPumpWrapped, <epmodel/StraightComponent/CoilWaterHeatingAirToWaterHeatPumpWrapped.hpp>, 0, 1)
EPMODELOBJECT_WRAP(AirLoopHVACUnitaryHeatPumpAirToAir, <epmodel/StraightComponent/AirLoopHVACUnitaryHeatPumpAirToAir.hpp>, 0, 1)
EPMODELOBJECT_WRAP(AirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed, <epmodel/StraightComponent/AirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed.hpp>, 0, 1)
EPMODELOBJECT_WRAP(AirLoopHVACUnitaryHeatCoolVAVChangeoverBypass, <epmodel/StraightComponent/AirLoopHVACUnitaryHeatCoolVAVChangeoverBypass.hpp>, 0, 1)
EPMODELOBJECT_WRAP(AirTerminalSingleDuctConstantVolumeCooledBeam, <epmodel/StraightComponent/AirTerminalSingleDuctConstantVolumeCooledBeam.hpp>, 0, 1)
EPMODELOBJECT_WRAP(AirTerminalSingleDuctConstantVolumeFourPipeBeam, <epmodel/StraightComponent/AirTerminalSingleDuctConstantVolumeFourPipeBeam.hpp>, 0, 1)
EPMODELOBJECT_WRAP(AirTerminalSingleDuctConstantVolumeFourPipeInduction, <epmodel/StraightComponent/AirTerminalSingleDuctConstantVolumeFourPipeInduction.hpp>, 0, 1)
EPMODELOBJECT_WRAP(AirTerminalSingleDuctVAVHeatAndCoolNoReheat, <epmodel/StraightComponent/AirTerminalSingleDuctVAVHeatAndCoolNoReheat.hpp>, 0, 1)
EPMODELOBJECT_WRAP(AirTerminalSingleDuctVAVNoReheat, <epmodel/StraightComponent/AirTerminalSingleDuctVAVNoReheat.hpp>, 0, 1)
EPMODELOBJECT_WRAP(AirTerminalSingleDuctVAVReheat, <epmodel/StraightComponent/AirTerminalSingleDuctVAVReheat.hpp>, 0, 1)
EPMODELOBJECT_WRAP(AirTerminalSingleDuctVAVHeatAndCoolReheat, <epmodel/StraightComponent/AirTerminalSingleDuctVAVHeatAndCoolReheat.hpp>, 0, 1)
EPMODELOBJECT_WRAP(BoilerHotWater, <epmodel/StraightComponent/BoilerHotWater.hpp>, 0, 1)
EPMODELOBJECT_WRAP(BoilerSteam, <epmodel/StraightComponent/BoilerSteam.hpp>, 0, 1)
EPMODELOBJECT_WRAP(RefrigerationCompressorRack, <epmodel/StraightComponent/RefrigerationCompressorRack.hpp>, 0, 1)
EPMODELOBJECT_WRAP(RefrigerationCondenserWaterCooled, <epmodel/StraightComponent/RefrigerationCondenserWaterCooled.hpp>, 0, 1)
EPMODELOBJECT_WRAP(DistrictCooling, <epmodel/StraightComponent/DistrictCooling.hpp>, 0, 1)
EPMODELOBJECT_WRAP(DistrictHeatingSteam, <epmodel/StraightComponent/DistrictHeatingSteam.hpp>, 0, 1)
EPMODELOBJECT_WRAP(DistrictHeatingWater, <epmodel/StraightComponent/DistrictHeatingWater.hpp>, 0, 1)
EPMODELOBJECT_WRAP(Duct, <epmodel/StraightComponent/Duct.hpp>, 0, 1)
EPMODELOBJECT_WRAP(PipeAdiabatic, <epmodel/StraightComponent/PipeAdiabatic.hpp>, 0, 1)
EPMODELOBJECT_WRAP(PipeIndoor, <epmodel/StraightComponent/PipeIndoor.hpp>, 0, 1)
EPMODELOBJECT_WRAP(PipeOutdoor, <epmodel/StraightComponent/PipeOutdoor.hpp>, 0, 1)
EPMODELOBJECT_WRAP(PumpConstantSpeed, <epmodel/StraightComponent/PumpConstantSpeed.hpp>, 0, 1)
EPMODELOBJECT_WRAP(PumpVariableSpeed, <epmodel/StraightComponent/PumpVariableSpeed.hpp>, 0, 1)
EPMODELOBJECT_WRAP(HeaderedPumpsConstantSpeed, <epmodel/StraightComponent/HeaderedPumpsConstantSpeed.hpp>, 0, 1)
EPMODELOBJECT_WRAP(HeaderedPumpsVariableSpeed, <epmodel/StraightComponent/HeaderedPumpsVariableSpeed.hpp>, 0, 1)
EPMODELOBJECT_WRAP(HumidifierSteamElectric, <epmodel/StraightComponent/HumidifierSteamElectric.hpp>, 0, 1)
EPMODELOBJECT_WRAP(HumidifierSteamGas, <epmodel/StraightComponent/HumidifierSteamGas.hpp>, 0, 1)
EPMODELOBJECT_WRAP(EvaporativeCoolerDirectResearchSpecial, <epmodel/StraightComponent/EvaporativeCoolerDirectResearchSpecial.hpp>, 0, 1)
EPMODELOBJECT_WRAP(EvaporativeCoolerIndirectResearchSpecial, <epmodel/StraightComponent/EvaporativeCoolerIndirectResearchSpecial.hpp>, 0, 1)
EPMODELOBJECT_WRAP(EvaporativeFluidCoolerSingleSpeed, <epmodel/StraightComponent/EvaporativeFluidCoolerSingleSpeed.hpp>, 0, 1)
EPMODELOBJECT_WRAP(EvaporativeFluidCoolerTwoSpeed, <epmodel/StraightComponent/EvaporativeFluidCoolerTwoSpeed.hpp>, 0, 1)
EPMODELOBJECT_WRAP(FluidCoolerSingleSpeed, <epmodel/StraightComponent/FluidCoolerSingleSpeed.hpp>, 0, 1)
EPMODELOBJECT_WRAP(FluidCoolerTwoSpeed, <epmodel/StraightComponent/FluidCoolerTwoSpeed.hpp>, 0, 1)
EPMODELOBJECT_WRAP(GroundHeatExchangerHorizontalTrench, <epmodel/StraightComponent/GroundHeatExchangerHorizontalTrench.hpp>, 0, 1)
EPMODELEXTENSIBLEGROUP_TEMPLATES(GFunction)
EPMODELOBJECT_WRAP(GroundHeatExchangerVertical, <epmodel/StraightComponent/GroundHeatExchangerVertical.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoolingTowerSingleSpeed, <epmodel/StraightComponent/CoolingTowerSingleSpeed.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoolingTowerTwoSpeed, <epmodel/StraightComponent/CoolingTowerTwoSpeed.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoolingTowerVariableSpeed, <epmodel/StraightComponent/CoolingTowerVariableSpeed.hpp>, 0, 1)
EPMODELOBJECT_WRAP(GeneratorFuelCellExhaustGasToWaterHeatExchanger, <epmodel/StraightComponent/GeneratorFuelCellExhaustGasToWaterHeatExchanger.hpp>, 0, 1)
EPMODELOBJECT_WRAP(GeneratorFuelCellStackCooler, <epmodel/StraightComponent/GeneratorFuelCellStackCooler.hpp>, 0, 1)
EPMODELOBJECT_WRAP(AirTerminalSingleDuctConstantVolumeNoReheat, <epmodel/StraightComponent/AirTerminalSingleDuctConstantVolumeNoReheat.hpp>, 0, 1)
EPMODELOBJECT_WRAP(AirTerminalSingleDuctConstantVolumeReheat, <epmodel/StraightComponent/AirTerminalSingleDuctConstantVolumeReheat.hpp>, 0, 1)
EPMODELOBJECT_WRAP(AirTerminalSingleDuctInletSideMixer, <epmodel/StraightComponent/AirTerminalSingleDuctInletSideMixer.hpp>, 0, 1)
EPMODELOBJECT_WRAP(AirTerminalSingleDuctParallelPIUReheat, <epmodel/StraightComponent/AirTerminalSingleDuctParallelPIUReheat.hpp>, 0, 1)
EPMODELOBJECT_WRAP(AirTerminalSingleDuctSeriesPIUReheat, <epmodel/StraightComponent/AirTerminalSingleDuctSeriesPIUReheat.hpp>, 0, 1)
EPMODELOBJECT_WRAP(FanComponentModel, <epmodel/StraightComponent/FanComponentModel.hpp>, 0, 1)
EPMODELOBJECT_WRAP(FanConstantVolume, <epmodel/StraightComponent/FanConstantVolume.hpp>, 0, 1)
EPMODELOBJECT_WRAP(FanOnOff, <epmodel/StraightComponent/FanOnOff.hpp>, 0, 1)
EPMODELEXTENSIBLEGROUP_TEMPLATES(FanSystemModelSpeed)
EPMODELOBJECT_WRAP(FanSystemModel, <epmodel/StraightComponent/FanSystemModel.hpp>, 0, 1)
EPMODELOBJECT_WRAP(FanVariableVolume, <epmodel/StraightComponent/FanVariableVolume.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoilCoolingDX, <epmodel/StraightComponent/CoilCoolingDX.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoilCoolingDXMultiSpeed, <epmodel/StraightComponent/CoilCoolingDXMultiSpeed.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoilCoolingDXSingleSpeed, <epmodel/StraightComponent/CoilCoolingDXSingleSpeed.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoilCoolingDXSingleSpeedThermalStorage, <epmodel/StraightComponent/CoilCoolingDXSingleSpeedThermalStorage.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoilCoolingDXVariableSpeed, <epmodel/StraightComponent/CoilCoolingDXVariableSpeed.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoilCoolingDXTwoSpeed, <epmodel/StraightComponent/CoilCoolingDXTwoSpeed.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoilCoolingDXTwoStageWithHumidityControlMode, <epmodel/StraightComponent/CoilCoolingDXTwoStageWithHumidityControlMode.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoilHeatingDXMultiSpeed, <epmodel/StraightComponent/CoilHeatingDXMultiSpeed.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoilHeatingDXSingleSpeed, <epmodel/StraightComponent/CoilHeatingDXSingleSpeed.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoilHeatingDXVariableSpeed, <epmodel/StraightComponent/CoilHeatingDXVariableSpeed.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoilHeatingDesuperheater, <epmodel/StraightComponent/CoilHeatingDesuperheater.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoilWaterHeatingDesuperheater, <epmodel/StraightComponent/CoilWaterHeatingDesuperheater.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoilHeatingElectric, <epmodel/StraightComponent/CoilHeatingElectric.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoilHeatingElectricMultiStage, <epmodel/StraightComponent/CoilHeatingElectricMultiStage.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoilHeatingGasMultiStage, <epmodel/StraightComponent/CoilHeatingGasMultiStage.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoilHeatingGas, <epmodel/StraightComponent/CoilHeatingGas.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoilSystemCoolingDXHeatExchangerAssisted, <epmodel/StraightComponent/CoilSystemCoolingDXHeatExchangerAssisted.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoilSystemIntegratedHeatPumpAirSource, <epmodel/StraightComponent/CoilSystemIntegratedHeatPumpAirSource.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoilSystemCoolingWater, <epmodel/StraightComponent/CoilSystemCoolingWater.hpp>, 0, 1)
EPMODELOBJECT_WRAP(CoilSystemCoolingWaterHeatExchangerAssisted, <epmodel/StraightComponent/CoilSystemCoolingWaterHeatExchangerAssisted.hpp>, 0, 1)
EPMODELOBJECT_WRAP(Node, <epmodel/StraightComponent/Node.hpp>, 0, 1)

#endif
