/***********************************************************************************************************************
*  OpenStudio(R), Copyright (c) Alliance for Energy Innovation, LLC.
*  See also https://openstudio.net/license
***********************************************************************************************************************/

#ifndef EPMODEL_HVACTEMPLATESYSTEMDUALDUCT_IMPL_HPP
#define EPMODEL_HVACTEMPLATESYSTEMDUALDUCT_IMPL_HPP

#include "ModelObject_Impl.hpp"

#include <vector>

namespace openstudio {
namespace epmodel {

namespace detail {

class EPMODEL_API HVACTemplateSystemDualDuct_Impl : public ModelObject_Impl
{
 public:
  using ModelObject_Impl::ModelObject_Impl;
  virtual ~HVACTemplateSystemDualDuct_Impl() override = default;

  std::string systemConfigurationType() const;
  boost::optional<double> mainSupplyFanMaximumFlowRate() const;
  double mainSupplyFanMinimumFlowFraction() const;
  double mainSupplyFanTotalEfficiency() const;
  double mainSupplyFanDeltaPressure() const;
  double mainSupplyFanMotorEfficiency() const;
  double mainSupplyFanMotorinAirStreamFraction() const;
  std::string mainSupplyFanPartLoadPowerCoefficients() const;
  boost::optional<double> coldDuctSupplyFanMaximumFlowRate() const;
  double coldDuctSupplyFanMinimumFlowFraction() const;
  double coldDuctSupplyFanTotalEfficiency() const;
  double coldDuctSupplyFanDeltaPressure() const;
  double coldDuctSupplyFanMotorEfficiency() const;
  double coldDuctSupplyFanMotorinAirStreamFraction() const;
  std::string coldDuctSupplyFanPartLoadPowerCoefficients() const;
  std::string coldDuctSupplyFanPlacement() const;
  boost::optional<double> hotDuctSupplyFanMaximumFlowRate() const;
  double hotDuctSupplyFanMinimumFlowFraction() const;
  double hotDuctSupplyFanTotalEfficiency() const;
  double hotDuctSupplyFanDeltaPressure() const;
  double hotDuctSupplyFanMotorEfficiency() const;
  double hotDuctSupplyFanMotorinAirStreamFraction() const;
  std::string hotDuctSupplyFanPartLoadPowerCoefficients() const;
  std::string hotDuctSupplyFanPlacement() const;
  std::string coolingCoilType() const;
  std::string coolingCoilSetpointControlType() const;
  double coolingCoilDesignSetpointTemperature() const;
  double coolingCoilSetpointatOutdoorDryBulbLow() const;
  double coolingCoilResetOutdoorDryBulbLow() const;
  double coolingCoilSetpointatOutdoorDryBulbHigh() const;
  double coolingCoilResetOutdoorDryBulbHigh() const;
  std::string heatingCoilType() const;
  std::string heatingCoilSetpointControlType() const;
  double heatingCoilDesignSetpoint() const;
  double heatingCoilSetpointatOutdoorDryBulbLow() const;
  double heatingCoilResetOutdoorDryBulbLow() const;
  double heatingCoilSetpointatOutdoorDryBulbHigh() const;
  double heatingCoilResetOutdoorDryBulbHigh() const;
  boost::optional<double> heatingCoilCapacity() const;
  double gasHeatingCoilEfficiency() const;
  double gasHeatingCoilParasiticElectricLoad() const;
  std::string preheatCoilType() const;
  double preheatCoilDesignSetpoint() const;
  double gasPreheatCoilEfficiency() const;
  double gasPreheatCoilParasiticElectricLoad() const;
  boost::optional<double> maximumOutdoorAirFlowRate() const;
  boost::optional<double> minimumOutdoorAirFlowRate() const;
  std::string minimumOutdoorAirControlType() const;
  std::string economizerType() const;
  std::string economizerLockout() const;
  boost::optional<double> economizerUpperTemperatureLimit() const;
  boost::optional<double> economizerLowerTemperatureLimit() const;
  boost::optional<double> economizerUpperEnthalpyLimit() const;
  boost::optional<double> economizerMaximumLimitDewpointTemperature() const;
  std::string nightCycleControl() const;
  std::string heatRecoveryType() const;
  double sensibleHeatRecoveryEffectiveness() const;
  double latentHeatRecoveryEffectiveness() const;
  std::string heatRecoveryHeatExchangerType() const;
  std::string heatRecoveryFrostControlType() const;
  std::string dehumidificationControlType() const;
  double dehumidificationRelativeHumiditySetpoint() const;
  std::string humidifierType() const;
  double humidifierRatedCapacity() const;
  boost::optional<double> humidifierRatedElectricPower() const;
  double humidifierRelativeHumiditySetpoint() const;
  std::string sizingOption() const;
  bool returnFan() const;
  double returnFanTotalEfficiency() const;
  double returnFanDeltaPressure() const;
  double returnFanMotorEfficiency() const;
  double returnFanMotorinAirStreamFraction() const;
  std::string returnFanPartLoadPowerCoefficients() const;

  bool isSystemConfigurationTypeDefaulted() const;
  bool isMainSupplyFanMaximumFlowRateDefaulted() const;
  bool isMainSupplyFanMinimumFlowFractionDefaulted() const;
  bool isMainSupplyFanTotalEfficiencyDefaulted() const;
  bool isMainSupplyFanDeltaPressureDefaulted() const;
  bool isMainSupplyFanMotorEfficiencyDefaulted() const;
  bool isMainSupplyFanMotorinAirStreamFractionDefaulted() const;
  bool isMainSupplyFanPartLoadPowerCoefficientsDefaulted() const;
  bool isColdDuctSupplyFanMaximumFlowRateDefaulted() const;
  bool isColdDuctSupplyFanMinimumFlowFractionDefaulted() const;
  bool isColdDuctSupplyFanTotalEfficiencyDefaulted() const;
  bool isColdDuctSupplyFanDeltaPressureDefaulted() const;
  bool isColdDuctSupplyFanMotorEfficiencyDefaulted() const;
  bool isColdDuctSupplyFanMotorinAirStreamFractionDefaulted() const;
  bool isColdDuctSupplyFanPartLoadPowerCoefficientsDefaulted() const;
  bool isColdDuctSupplyFanPlacementDefaulted() const;
  bool isHotDuctSupplyFanMaximumFlowRateDefaulted() const;
  bool isHotDuctSupplyFanMinimumFlowFractionDefaulted() const;
  bool isHotDuctSupplyFanTotalEfficiencyDefaulted() const;
  bool isHotDuctSupplyFanDeltaPressureDefaulted() const;
  bool isHotDuctSupplyFanMotorEfficiencyDefaulted() const;
  bool isHotDuctSupplyFanMotorinAirStreamFractionDefaulted() const;
  bool isHotDuctSupplyFanPartLoadPowerCoefficientsDefaulted() const;
  bool isHotDuctSupplyFanPlacementDefaulted() const;
  bool isCoolingCoilTypeDefaulted() const;
  bool isCoolingCoilSetpointControlTypeDefaulted() const;
  bool isCoolingCoilDesignSetpointTemperatureDefaulted() const;
  bool isCoolingCoilSetpointatOutdoorDryBulbLowDefaulted() const;
  bool isCoolingCoilResetOutdoorDryBulbLowDefaulted() const;
  bool isCoolingCoilSetpointatOutdoorDryBulbHighDefaulted() const;
  bool isCoolingCoilResetOutdoorDryBulbHighDefaulted() const;
  bool isHeatingCoilTypeDefaulted() const;
  bool isHeatingCoilSetpointControlTypeDefaulted() const;
  bool isHeatingCoilDesignSetpointDefaulted() const;
  bool isHeatingCoilSetpointatOutdoorDryBulbLowDefaulted() const;
  bool isHeatingCoilResetOutdoorDryBulbLowDefaulted() const;
  bool isHeatingCoilSetpointatOutdoorDryBulbHighDefaulted() const;
  bool isHeatingCoilResetOutdoorDryBulbHighDefaulted() const;
  bool isHeatingCoilCapacityDefaulted() const;
  bool isGasHeatingCoilEfficiencyDefaulted() const;
  bool isGasHeatingCoilParasiticElectricLoadDefaulted() const;
  bool isPreheatCoilTypeDefaulted() const;
  bool isPreheatCoilDesignSetpointDefaulted() const;
  bool isGasPreheatCoilEfficiencyDefaulted() const;
  bool isGasPreheatCoilParasiticElectricLoadDefaulted() const;
  bool isMaximumOutdoorAirFlowRateDefaulted() const;
  bool isMinimumOutdoorAirFlowRateDefaulted() const;
  bool isMinimumOutdoorAirControlTypeDefaulted() const;
  bool isEconomizerTypeDefaulted() const;
  bool isEconomizerLockoutDefaulted() const;
  bool isEconomizerUpperTemperatureLimitDefaulted() const;
  bool isEconomizerLowerTemperatureLimitDefaulted() const;
  bool isEconomizerUpperEnthalpyLimitDefaulted() const;
  bool isEconomizerMaximumLimitDewpointTemperatureDefaulted() const;
  bool isNightCycleControlDefaulted() const;
  bool isHeatRecoveryTypeDefaulted() const;
  bool isSensibleHeatRecoveryEffectivenessDefaulted() const;
  bool isLatentHeatRecoveryEffectivenessDefaulted() const;
  bool isHeatRecoveryHeatExchangerTypeDefaulted() const;
  bool isHeatRecoveryFrostControlTypeDefaulted() const;
  bool isDehumidificationControlTypeDefaulted() const;
  bool isDehumidificationRelativeHumiditySetpointDefaulted() const;
  bool isHumidifierTypeDefaulted() const;
  bool isHumidifierRatedCapacityDefaulted() const;
  bool isHumidifierRatedElectricPowerDefaulted() const;
  bool isHumidifierRelativeHumiditySetpointDefaulted() const;
  bool isSizingOptionDefaulted() const;
  bool isReturnFanDefaulted() const;
  bool isReturnFanTotalEfficiencyDefaulted() const;
  bool isReturnFanDeltaPressureDefaulted() const;
  bool isReturnFanMotorEfficiencyDefaulted() const;
  bool isReturnFanMotorinAirStreamFractionDefaulted() const;
  bool isReturnFanPartLoadPowerCoefficientsDefaulted() const;

  bool isMainSupplyFanMaximumFlowRateAutosized() const;
  bool isColdDuctSupplyFanMaximumFlowRateAutosized() const;
  bool isHotDuctSupplyFanMaximumFlowRateAutosized() const;
  bool isHeatingCoilCapacityAutosized() const;
  bool isMaximumOutdoorAirFlowRateAutosized() const;
  bool isMinimumOutdoorAirFlowRateAutosized() const;
  bool isHumidifierRatedElectricPowerAutosized() const;

  bool setSystemConfigurationType(const std::string& systemConfigurationType);
  bool setMainSupplyFanMaximumFlowRate(double mainSupplyFanMaximumFlowRate);
  bool setMainSupplyFanMinimumFlowFraction(double mainSupplyFanMinimumFlowFraction);
  bool setMainSupplyFanTotalEfficiency(double mainSupplyFanTotalEfficiency);
  bool setMainSupplyFanDeltaPressure(double mainSupplyFanDeltaPressure);
  bool setMainSupplyFanMotorEfficiency(double mainSupplyFanMotorEfficiency);
  bool setMainSupplyFanMotorinAirStreamFraction(double mainSupplyFanMotorinAirStreamFraction);
  bool setMainSupplyFanPartLoadPowerCoefficients(const std::string& mainSupplyFanPartLoadPowerCoefficients);
  bool setColdDuctSupplyFanMaximumFlowRate(double coldDuctSupplyFanMaximumFlowRate);
  bool setColdDuctSupplyFanMinimumFlowFraction(double coldDuctSupplyFanMinimumFlowFraction);
  bool setColdDuctSupplyFanTotalEfficiency(double coldDuctSupplyFanTotalEfficiency);
  bool setColdDuctSupplyFanDeltaPressure(double coldDuctSupplyFanDeltaPressure);
  bool setColdDuctSupplyFanMotorEfficiency(double coldDuctSupplyFanMotorEfficiency);
  bool setColdDuctSupplyFanMotorinAirStreamFraction(double coldDuctSupplyFanMotorinAirStreamFraction);
  bool setColdDuctSupplyFanPartLoadPowerCoefficients(const std::string& coldDuctSupplyFanPartLoadPowerCoefficients);
  bool setColdDuctSupplyFanPlacement(const std::string& coldDuctSupplyFanPlacement);
  bool setHotDuctSupplyFanMaximumFlowRate(double hotDuctSupplyFanMaximumFlowRate);
  bool setHotDuctSupplyFanMinimumFlowFraction(double hotDuctSupplyFanMinimumFlowFraction);
  bool setHotDuctSupplyFanTotalEfficiency(double hotDuctSupplyFanTotalEfficiency);
  bool setHotDuctSupplyFanDeltaPressure(double hotDuctSupplyFanDeltaPressure);
  bool setHotDuctSupplyFanMotorEfficiency(double hotDuctSupplyFanMotorEfficiency);
  bool setHotDuctSupplyFanMotorinAirStreamFraction(double hotDuctSupplyFanMotorinAirStreamFraction);
  bool setHotDuctSupplyFanPartLoadPowerCoefficients(const std::string& hotDuctSupplyFanPartLoadPowerCoefficients);
  bool setHotDuctSupplyFanPlacement(const std::string& hotDuctSupplyFanPlacement);
  bool setCoolingCoilType(const std::string& coolingCoilType);
  bool setCoolingCoilSetpointControlType(const std::string& coolingCoilSetpointControlType);
  bool setCoolingCoilDesignSetpointTemperature(double coolingCoilDesignSetpointTemperature);
  bool setCoolingCoilSetpointatOutdoorDryBulbLow(double coolingCoilSetpointatOutdoorDryBulbLow);
  bool setCoolingCoilResetOutdoorDryBulbLow(double coolingCoilResetOutdoorDryBulbLow);
  bool setCoolingCoilSetpointatOutdoorDryBulbHigh(double coolingCoilSetpointatOutdoorDryBulbHigh);
  bool setCoolingCoilResetOutdoorDryBulbHigh(double coolingCoilResetOutdoorDryBulbHigh);
  bool setHeatingCoilType(const std::string& heatingCoilType);
  bool setHeatingCoilSetpointControlType(const std::string& heatingCoilSetpointControlType);
  bool setHeatingCoilDesignSetpoint(double heatingCoilDesignSetpoint);
  bool setHeatingCoilSetpointatOutdoorDryBulbLow(double heatingCoilSetpointatOutdoorDryBulbLow);
  bool setHeatingCoilResetOutdoorDryBulbLow(double heatingCoilResetOutdoorDryBulbLow);
  bool setHeatingCoilSetpointatOutdoorDryBulbHigh(double heatingCoilSetpointatOutdoorDryBulbHigh);
  bool setHeatingCoilResetOutdoorDryBulbHigh(double heatingCoilResetOutdoorDryBulbHigh);
  bool setHeatingCoilCapacity(double heatingCoilCapacity);
  bool setGasHeatingCoilEfficiency(double gasHeatingCoilEfficiency);
  bool setGasHeatingCoilParasiticElectricLoad(double gasHeatingCoilParasiticElectricLoad);
  bool setPreheatCoilType(const std::string& preheatCoilType);
  bool setPreheatCoilDesignSetpoint(double preheatCoilDesignSetpoint);
  bool setGasPreheatCoilEfficiency(double gasPreheatCoilEfficiency);
  bool setGasPreheatCoilParasiticElectricLoad(double gasPreheatCoilParasiticElectricLoad);
  bool setMaximumOutdoorAirFlowRate(double maximumOutdoorAirFlowRate);
  bool setMinimumOutdoorAirFlowRate(double minimumOutdoorAirFlowRate);
  bool setMinimumOutdoorAirControlType(const std::string& minimumOutdoorAirControlType);
  bool setEconomizerType(const std::string& economizerType);
  bool setEconomizerLockout(const std::string& economizerLockout);
  bool setEconomizerUpperTemperatureLimit(double economizerUpperTemperatureLimit);
  bool setEconomizerLowerTemperatureLimit(double economizerLowerTemperatureLimit);
  bool setEconomizerUpperEnthalpyLimit(double economizerUpperEnthalpyLimit);
  bool setEconomizerMaximumLimitDewpointTemperature(double economizerMaximumLimitDewpointTemperature);
  bool setNightCycleControl(const std::string& nightCycleControl);
  bool setHeatRecoveryType(const std::string& heatRecoveryType);
  bool setSensibleHeatRecoveryEffectiveness(double sensibleHeatRecoveryEffectiveness);
  bool setLatentHeatRecoveryEffectiveness(double latentHeatRecoveryEffectiveness);
  bool setHeatRecoveryHeatExchangerType(const std::string& heatRecoveryHeatExchangerType);
  bool setHeatRecoveryFrostControlType(const std::string& heatRecoveryFrostControlType);
  bool setDehumidificationControlType(const std::string& dehumidificationControlType);
  bool setDehumidificationRelativeHumiditySetpoint(double dehumidificationRelativeHumiditySetpoint);
  bool setHumidifierType(const std::string& humidifierType);
  bool setHumidifierRatedCapacity(double humidifierRatedCapacity);
  bool setHumidifierRatedElectricPower(double humidifierRatedElectricPower);
  bool setHumidifierRelativeHumiditySetpoint(double humidifierRelativeHumiditySetpoint);
  bool setSizingOption(const std::string& sizingOption);
  bool setReturnFan(bool returnFan);
  bool setReturnFanTotalEfficiency(double returnFanTotalEfficiency);
  bool setReturnFanDeltaPressure(double returnFanDeltaPressure);
  bool setReturnFanMotorEfficiency(double returnFanMotorEfficiency);
  bool setReturnFanMotorinAirStreamFraction(double returnFanMotorinAirStreamFraction);
  bool setReturnFanPartLoadPowerCoefficients(const std::string& returnFanPartLoadPowerCoefficients);

  void resetSystemConfigurationType();
  void resetMainSupplyFanMaximumFlowRate();
  void resetMainSupplyFanMinimumFlowFraction();
  void resetMainSupplyFanTotalEfficiency();
  void resetMainSupplyFanDeltaPressure();
  void resetMainSupplyFanMotorEfficiency();
  void resetMainSupplyFanMotorinAirStreamFraction();
  void resetMainSupplyFanPartLoadPowerCoefficients();
  void resetColdDuctSupplyFanMaximumFlowRate();
  void resetColdDuctSupplyFanMinimumFlowFraction();
  void resetColdDuctSupplyFanTotalEfficiency();
  void resetColdDuctSupplyFanDeltaPressure();
  void resetColdDuctSupplyFanMotorEfficiency();
  void resetColdDuctSupplyFanMotorinAirStreamFraction();
  void resetColdDuctSupplyFanPartLoadPowerCoefficients();
  void resetColdDuctSupplyFanPlacement();
  void resetHotDuctSupplyFanMaximumFlowRate();
  void resetHotDuctSupplyFanMinimumFlowFraction();
  void resetHotDuctSupplyFanTotalEfficiency();
  void resetHotDuctSupplyFanDeltaPressure();
  void resetHotDuctSupplyFanMotorEfficiency();
  void resetHotDuctSupplyFanMotorinAirStreamFraction();
  void resetHotDuctSupplyFanPartLoadPowerCoefficients();
  void resetHotDuctSupplyFanPlacement();
  void resetCoolingCoilType();
  void resetCoolingCoilSetpointControlType();
  void resetCoolingCoilDesignSetpointTemperature();
  void resetCoolingCoilSetpointatOutdoorDryBulbLow();
  void resetCoolingCoilResetOutdoorDryBulbLow();
  void resetCoolingCoilSetpointatOutdoorDryBulbHigh();
  void resetCoolingCoilResetOutdoorDryBulbHigh();
  void resetHeatingCoilType();
  void resetHeatingCoilSetpointControlType();
  void resetHeatingCoilDesignSetpoint();
  void resetHeatingCoilSetpointatOutdoorDryBulbLow();
  void resetHeatingCoilResetOutdoorDryBulbLow();
  void resetHeatingCoilSetpointatOutdoorDryBulbHigh();
  void resetHeatingCoilResetOutdoorDryBulbHigh();
  void resetHeatingCoilCapacity();
  void resetGasHeatingCoilEfficiency();
  void resetGasHeatingCoilParasiticElectricLoad();
  void resetPreheatCoilType();
  void resetPreheatCoilDesignSetpoint();
  void resetGasPreheatCoilEfficiency();
  void resetGasPreheatCoilParasiticElectricLoad();
  void resetMaximumOutdoorAirFlowRate();
  void resetMinimumOutdoorAirFlowRate();
  void resetMinimumOutdoorAirControlType();
  void resetEconomizerType();
  void resetEconomizerLockout();
  void resetEconomizerUpperTemperatureLimit();
  void resetEconomizerLowerTemperatureLimit();
  void resetEconomizerUpperEnthalpyLimit();
  void resetEconomizerMaximumLimitDewpointTemperature();
  void resetNightCycleControl();
  void resetHeatRecoveryType();
  void resetSensibleHeatRecoveryEffectiveness();
  void resetLatentHeatRecoveryEffectiveness();
  void resetHeatRecoveryHeatExchangerType();
  void resetHeatRecoveryFrostControlType();
  void resetDehumidificationControlType();
  void resetDehumidificationRelativeHumiditySetpoint();
  void resetHumidifierType();
  void resetHumidifierRatedCapacity();
  void resetHumidifierRatedElectricPower();
  void resetHumidifierRelativeHumiditySetpoint();
  void resetSizingOption();
  void resetReturnFan();
  void resetReturnFanTotalEfficiency();
  void resetReturnFanDeltaPressure();
  void resetReturnFanMotorEfficiency();
  void resetReturnFanMotorinAirStreamFraction();
  void resetReturnFanPartLoadPowerCoefficients();

  void autosizeMainSupplyFanMaximumFlowRate();
  void autosizeColdDuctSupplyFanMaximumFlowRate();
  void autosizeHotDuctSupplyFanMaximumFlowRate();
  void autosizeHeatingCoilCapacity();
  void autosizeMaximumOutdoorAirFlowRate();
  void autosizeMinimumOutdoorAirFlowRate();
  void autosizeHumidifierRatedElectricPower();

  std::vector<std::string> systemConfigurationTypeValues() const;
  std::vector<std::string> mainSupplyFanPartLoadPowerCoefficientsValues() const;
  std::vector<std::string> coldDuctSupplyFanPartLoadPowerCoefficientsValues() const;
  std::vector<std::string> coldDuctSupplyFanPlacementValues() const;
  std::vector<std::string> hotDuctSupplyFanPartLoadPowerCoefficientsValues() const;
  std::vector<std::string> hotDuctSupplyFanPlacementValues() const;
  std::vector<std::string> coolingCoilTypeValues() const;
  std::vector<std::string> coolingCoilSetpointControlTypeValues() const;
  std::vector<std::string> heatingCoilTypeValues() const;
  std::vector<std::string> heatingCoilSetpointControlTypeValues() const;
  std::vector<std::string> preheatCoilTypeValues() const;
  std::vector<std::string> minimumOutdoorAirControlTypeValues() const;
  std::vector<std::string> economizerTypeValues() const;
  std::vector<std::string> economizerLockoutValues() const;
  std::vector<std::string> nightCycleControlValues() const;
  std::vector<std::string> heatRecoveryTypeValues() const;
  std::vector<std::string> heatRecoveryHeatExchangerTypeValues() const;
  std::vector<std::string> heatRecoveryFrostControlTypeValues() const;
  std::vector<std::string> dehumidificationControlTypeValues() const;
  std::vector<std::string> humidifierTypeValues() const;
  std::vector<std::string> sizingOptionValues() const;
  std::vector<std::string> returnFanPartLoadPowerCoefficientsValues() const;
};

}  // namespace detail
}  // namespace epmodel
}  // namespace openstudio

#endif
