/***********************************************************************************************************************
*  OpenStudio(R), Copyright (c) Alliance for Energy Innovation, LLC.
*  See also https://openstudio.net/license
***********************************************************************************************************************/

#ifndef EPMODEL_REFRIGERATIONSYSTEM_HPP
#define EPMODEL_REFRIGERATIONSYSTEM_HPP

#include "EPModelAPI.hpp"
#include "ModelObject.hpp"

#include <memory>
#include <string>
#include <vector>

namespace openstudio {
namespace epmodel {

  class Model;

  namespace detail {
    class RefrigerationSystem_Impl;
  }

  class EPMODEL_API RefrigerationSystem : public ModelObject
  {
   public:
    explicit RefrigerationSystem(const Model& model);

    virtual ~RefrigerationSystem() override = default;
    RefrigerationSystem(const RefrigerationSystem& other) = default;
    RefrigerationSystem(RefrigerationSystem&& other) = default;
    RefrigerationSystem& operator=(const RefrigerationSystem&) = default;
    RefrigerationSystem& operator=(RefrigerationSystem&&) = default;

    static IddObjectType iddObjectType();

    static std::vector<std::string> refrigerationSystemWorkingFluidTypeValues();
    static std::vector<std::string> suctionTemperatureControlTypeValues();
    static std::vector<std::string> intercoolerTypeValues();

    // Schema Alignment Notes:
    // - API: Preserve openstudio::model scalar accessor names/signatures for this model-counterpart class.
    // - Field Mapping: Map minimumCondensingTemperature, refrigerationSystemWorkingFluidType, suctionTemperatureControlType,
    //   endUseSubcategory, intercoolerType, sumUASuctionPiping, and shellandCoilIntercoolerEffectiveness directly to the
    //   Refrigeration:System fields enumerated in Refrigeration_System_FieldEnums.
    // - Field Mapping: Choice values helpers mirror IDD key lookups (IddFactory/getIddKeyNames) to keep API parity.
    // - Field Mapping: Relationship references (case/walk-in lists, transfer load lists, condenser/compressor references,
    //   mechanical/liquid subcoolers, suction piping zone, and compressor lists) remain excluded while scalar coverage is
    //   being built.  Transfer load lists correspond to Refrigeration:TransferLoadList objects (name only) generated by the
    //   EnergyPlus translator from secondary system/cascade condenser relationships, so there are no additional scalar APIs.
    // - TODO(parity): Expose richer relationship APIs once scalar saturation is complete.
    double minimumCondensingTemperature() const;
    bool setMinimumCondensingTemperature(double minimumCondensingTemperature);

    std::string refrigerationSystemWorkingFluidType() const;
    bool setRefrigerationSystemWorkingFluidType(const std::string& refrigerationSystemWorkingFluidType);

    std::string suctionTemperatureControlType() const;
    bool setSuctionTemperatureControlType(const std::string& suctionTemperatureControlType);
    bool isSuctionTemperatureControlTypeDefaulted() const;
    void resetSuctionTemperatureControlType();

    std::string endUseSubcategory() const;
    bool setEndUseSubcategory(const std::string& endUseSubcategory);
    bool isEndUseSubcategoryDefaulted() const;
    void resetEndUseSubcategory();

    std::string intercoolerType() const;
    bool setIntercoolerType(const std::string& intercoolerType);
    bool isIntercoolerTypeDefaulted() const;
    void resetIntercoolerType();

    double sumUASuctionPiping() const;
    bool setSumUASuctionPiping(double sumUASuctionPiping);
    bool isSumUASuctionPipingDefaulted() const;
    void resetSumUASuctionPiping();

    double shellandCoilIntercoolerEffectiveness() const;
    bool setShellandCoilIntercoolerEffectiveness(double shellandCoilIntercoolerEffectiveness);
    bool isShellandCoilIntercoolerEffectivenessDefaulted() const;
    void resetShellandCoilIntercoolerEffectiveness();

   protected:
    using ImplType = detail::RefrigerationSystem_Impl;

    friend class Model;
    friend class openstudio::IdfObject;
    friend class openstudio::detail::IdfObject_Impl;

    explicit RefrigerationSystem(std::shared_ptr<detail::RefrigerationSystem_Impl> impl);
  };

}  // namespace epmodel
}  // namespace openstudio

#endif  // EPMODEL_REFRIGERATIONSYSTEM_HPP
