#include <ruby.h>

extern "C" {
  void Init_openstudioepmodel(void);
  void Init_openstudioepmodelmodelobject(void);
  void Init_openstudioepmodelresourceobject(void);
  void Init_openstudioepmodelplantequipmentoperationscheme(void);
  void Init_openstudioepmodelparentobject(void);
  void Init_openstudioepmodelgaslayer(void);
  void Init_openstudioepmodelshadingmaterial(void);
  void Init_openstudioepmodelairflownetworklinkage(void);
  void Init_openstudioepmodelairflownetworknode(void);
  void Init_openstudioepmodelavailabilitymanager(void);
  void Init_openstudioepmodelexteriorloadinstance(void);
  void Init_openstudioepmodelschedule(void);
  void Init_openstudioepmodelschedulebase(void);
  void Init_openstudioepmodelspaceloadinstance(void);
  void Init_openstudioepmodelspaceload(void);
  void Init_openstudioepmodelopaquematerial(void);
  void Init_openstudioepmodelmodelpartitionmaterial(void);
  void Init_openstudioepmodelthermostat(void);
  void Init_openstudioepmodelsizingperiod(void);
  void Init_openstudioepmodellayeredconstruction(void);
  void Init_openstudioepmodelconstructionbase(void);
  void Init_openstudioepmodelinverter(void);
  void Init_openstudioepmodelelectricalstorage(void);
  void Init_openstudioepmodelplanarsurface(void);
  void Init_openstudioepmodelgenerator(void);
  void Init_openstudioepmodelphotovoltaicperformance(void);
  void Init_openstudioepmodelglazing(void);
  void Init_openstudioepmodelplanarsurfacegroup(void);
  void Init_openstudioepmodelcurve(void);
  void Init_openstudioepmodelhvaccomponent(void);
  void Init_openstudioepmodelscheduleinterval(void);
  void Init_openstudioepmodelloop(void);
  void Init_openstudioepmodelstraightcomponent(void);
  void Init_openstudioepmodelwatertoaircomponent(void);
  void Init_openstudioepmodelzonehvaccomponent(void);
  void Init_openstudioepmodelwatertowatercomponent(void);
  void Init_openstudioepmodelairtoaircomponent(void);
  void Init_openstudioepmodelmixer(void);
  void Init_openstudioepmodelsplitter(void);
  void Init_openstudioepmodelsetpointmanager(void);
}

namespace openstudio {
namespace ruby {

void initEpModelRubyBindings() {
  Init_openstudioepmodel();
  rb_provide("openstudioepmodel");
  rb_provide("openstudioepmodel.so");
  Init_openstudioepmodelmodelobject();
  rb_provide("openstudioepmodelmodelobject");
  rb_provide("openstudioepmodelmodelobject.so");
  Init_openstudioepmodelresourceobject();
  rb_provide("openstudioepmodelresourceobject");
  rb_provide("openstudioepmodelresourceobject.so");
  Init_openstudioepmodelplantequipmentoperationscheme();
  rb_provide("openstudioepmodelplantequipmentoperationscheme");
  rb_provide("openstudioepmodelplantequipmentoperationscheme.so");
  Init_openstudioepmodelparentobject();
  rb_provide("openstudioepmodelparentobject");
  rb_provide("openstudioepmodelparentobject.so");
  Init_openstudioepmodelgaslayer();
  rb_provide("openstudioepmodelgaslayer");
  rb_provide("openstudioepmodelgaslayer.so");
  Init_openstudioepmodelshadingmaterial();
  rb_provide("openstudioepmodelshadingmaterial");
  rb_provide("openstudioepmodelshadingmaterial.so");
  Init_openstudioepmodelairflownetworklinkage();
  rb_provide("openstudioepmodelairflownetworklinkage");
  rb_provide("openstudioepmodelairflownetworklinkage.so");
  Init_openstudioepmodelairflownetworknode();
  rb_provide("openstudioepmodelairflownetworknode");
  rb_provide("openstudioepmodelairflownetworknode.so");
  Init_openstudioepmodelavailabilitymanager();
  rb_provide("openstudioepmodelavailabilitymanager");
  rb_provide("openstudioepmodelavailabilitymanager.so");
  Init_openstudioepmodelexteriorloadinstance();
  rb_provide("openstudioepmodelexteriorloadinstance");
  rb_provide("openstudioepmodelexteriorloadinstance.so");
  Init_openstudioepmodelschedule();
  rb_provide("openstudioepmodelschedule");
  rb_provide("openstudioepmodelschedule.so");
  Init_openstudioepmodelschedulebase();
  rb_provide("openstudioepmodelschedulebase");
  rb_provide("openstudioepmodelschedulebase.so");
  Init_openstudioepmodelspaceloadinstance();
  rb_provide("openstudioepmodelspaceloadinstance");
  rb_provide("openstudioepmodelspaceloadinstance.so");
  Init_openstudioepmodelspaceload();
  rb_provide("openstudioepmodelspaceload");
  rb_provide("openstudioepmodelspaceload.so");
  Init_openstudioepmodelopaquematerial();
  rb_provide("openstudioepmodelopaquematerial");
  rb_provide("openstudioepmodelopaquematerial.so");
  Init_openstudioepmodelmodelpartitionmaterial();
  rb_provide("openstudioepmodelmodelpartitionmaterial");
  rb_provide("openstudioepmodelmodelpartitionmaterial.so");
  Init_openstudioepmodelthermostat();
  rb_provide("openstudioepmodelthermostat");
  rb_provide("openstudioepmodelthermostat.so");
  Init_openstudioepmodelsizingperiod();
  rb_provide("openstudioepmodelsizingperiod");
  rb_provide("openstudioepmodelsizingperiod.so");
  Init_openstudioepmodellayeredconstruction();
  rb_provide("openstudioepmodellayeredconstruction");
  rb_provide("openstudioepmodellayeredconstruction.so");
  Init_openstudioepmodelconstructionbase();
  rb_provide("openstudioepmodelconstructionbase");
  rb_provide("openstudioepmodelconstructionbase.so");
  Init_openstudioepmodelinverter();
  rb_provide("openstudioepmodelinverter");
  rb_provide("openstudioepmodelinverter.so");
  Init_openstudioepmodelelectricalstorage();
  rb_provide("openstudioepmodelelectricalstorage");
  rb_provide("openstudioepmodelelectricalstorage.so");
  Init_openstudioepmodelplanarsurface();
  rb_provide("openstudioepmodelplanarsurface");
  rb_provide("openstudioepmodelplanarsurface.so");
  Init_openstudioepmodelgenerator();
  rb_provide("openstudioepmodelgenerator");
  rb_provide("openstudioepmodelgenerator.so");
  Init_openstudioepmodelphotovoltaicperformance();
  rb_provide("openstudioepmodelphotovoltaicperformance");
  rb_provide("openstudioepmodelphotovoltaicperformance.so");
  Init_openstudioepmodelglazing();
  rb_provide("openstudioepmodelglazing");
  rb_provide("openstudioepmodelglazing.so");
  Init_openstudioepmodelplanarsurfacegroup();
  rb_provide("openstudioepmodelplanarsurfacegroup");
  rb_provide("openstudioepmodelplanarsurfacegroup.so");
  Init_openstudioepmodelcurve();
  rb_provide("openstudioepmodelcurve");
  rb_provide("openstudioepmodelcurve.so");
  Init_openstudioepmodelhvaccomponent();
  rb_provide("openstudioepmodelhvaccomponent");
  rb_provide("openstudioepmodelhvaccomponent.so");
  Init_openstudioepmodelscheduleinterval();
  rb_provide("openstudioepmodelscheduleinterval");
  rb_provide("openstudioepmodelscheduleinterval.so");
  Init_openstudioepmodelloop();
  rb_provide("openstudioepmodelloop");
  rb_provide("openstudioepmodelloop.so");
  Init_openstudioepmodelstraightcomponent();
  rb_provide("openstudioepmodelstraightcomponent");
  rb_provide("openstudioepmodelstraightcomponent.so");
  Init_openstudioepmodelwatertoaircomponent();
  rb_provide("openstudioepmodelwatertoaircomponent");
  rb_provide("openstudioepmodelwatertoaircomponent.so");
  Init_openstudioepmodelzonehvaccomponent();
  rb_provide("openstudioepmodelzonehvaccomponent");
  rb_provide("openstudioepmodelzonehvaccomponent.so");
  Init_openstudioepmodelwatertowatercomponent();
  rb_provide("openstudioepmodelwatertowatercomponent");
  rb_provide("openstudioepmodelwatertowatercomponent.so");
  Init_openstudioepmodelairtoaircomponent();
  rb_provide("openstudioepmodelairtoaircomponent");
  rb_provide("openstudioepmodelairtoaircomponent.so");
  Init_openstudioepmodelmixer();
  rb_provide("openstudioepmodelmixer");
  rb_provide("openstudioepmodelmixer.so");
  Init_openstudioepmodelsplitter();
  rb_provide("openstudioepmodelsplitter");
  rb_provide("openstudioepmodelsplitter.so");
  Init_openstudioepmodelsetpointmanager();
  rb_provide("openstudioepmodelsetpointmanager");
  rb_provide("openstudioepmodelsetpointmanager.so");
}

} // namespace ruby
} // namespace openstudio
