#ifndef EPMODEL_PlantEquipmentOperationScheme_I
#define EPMODEL_PlantEquipmentOperationScheme_I

#ifdef SWIGPYTHON
  %module openstudioepmodelplantequipmentoperationscheme
#endif

%include <epmodel/EPModel_Common_Include.i>
%import <epmodel/EPModel.i>

EPMODELOBJECT_WRAP(PlantEquipmentOperationScheme, <epmodel/PlantEquipmentOperationScheme/PlantEquipmentOperationScheme.hpp>)
EPMODELOBJECT_WRAP(PlantEquipmentOperationChillerHeaterChangeover, <epmodel/PlantEquipmentOperationScheme/PlantEquipmentOperationChillerHeaterChangeover.hpp>)
EPMODELOBJECT_WRAP(PlantEquipmentOperationComponentSetpoint, <epmodel/PlantEquipmentOperationScheme/PlantEquipmentOperationComponentSetpoint.hpp>)
EPMODELOBJECT_WRAP(PlantEquipmentOperationThermalEnergyStorage, <epmodel/PlantEquipmentOperationScheme/PlantEquipmentOperationThermalEnergyStorage.hpp>)
EPMODELOBJECT_WRAP(PlantEquipmentOperationUncontrolled, <epmodel/PlantEquipmentOperationScheme/PlantEquipmentOperationUncontrolled.hpp>)
EPMODELOBJECT_WRAP(PlantEquipmentOperationUserDefined, <epmodel/PlantEquipmentOperationScheme/PlantEquipmentOperationUserDefined.hpp>)
EPMODELOBJECT_WRAP(PlantEquipmentOperationCoolingLoad, <epmodel/PlantEquipmentOperationScheme/PlantEquipmentOperationCoolingLoad.hpp>)
EPMODELOBJECT_WRAP(PlantEquipmentOperationHeatingLoad, <epmodel/PlantEquipmentOperationScheme/PlantEquipmentOperationHeatingLoad.hpp>)
EPMODELOBJECT_WRAP(PlantEquipmentOperationOutdoorDewpoint, <epmodel/PlantEquipmentOperationScheme/PlantEquipmentOperationOutdoorDewpoint.hpp>)
EPMODELOBJECT_WRAP(PlantEquipmentOperationOutdoorDewpointDifference, <epmodel/PlantEquipmentOperationScheme/PlantEquipmentOperationOutdoorDewpointDifference.hpp>)
EPMODELOBJECT_WRAP(PlantEquipmentOperationOutdoorDryBulbDifference, <epmodel/PlantEquipmentOperationScheme/PlantEquipmentOperationOutdoorDryBulbDifference.hpp>)
EPMODELOBJECT_WRAP(PlantEquipmentOperationOutdoorWetBulbDifference, <epmodel/PlantEquipmentOperationScheme/PlantEquipmentOperationOutdoorWetBulbDifference.hpp>)
EPMODELOBJECT_WRAP(PlantEquipmentOperationOutdoorDryBulb, <epmodel/PlantEquipmentOperationScheme/PlantEquipmentOperationOutdoorDryBulb.hpp>)
EPMODELOBJECT_WRAP(PlantEquipmentOperationOutdoorRelativeHumidity, <epmodel/PlantEquipmentOperationScheme/PlantEquipmentOperationOutdoorRelativeHumidity.hpp>)
EPMODELOBJECT_WRAP(PlantEquipmentOperationOutdoorWetBulb, <epmodel/PlantEquipmentOperationScheme/PlantEquipmentOperationOutdoorWetBulb.hpp>)

#endif
