#ifndef EPMODEL_ZoneHVACComponent_I
#define EPMODEL_ZoneHVACComponent_I

#ifdef SWIGPYTHON
  %module openstudioepmodelzonehvaccomponent
#endif

%include <epmodel/EPModel_Common_Include.i>
%import <epmodel/EPModel.i>
%import <epmodel/HVACComponent/EPModelHVACComponent.i>

EPMODELOBJECT_WRAP(ZoneHVACComponent, <epmodel/ZoneHVACComponent/ZoneHVACComponent.hpp>)
EPMODELOBJECT_WRAP(AirLoopHVACUnitarySystem, <epmodel/ZoneHVACComponent/AirLoopHVACUnitarySystem.hpp>)
EPMODELOBJECT_WRAP(ZoneHVACBaseboardConvectiveElectric, <epmodel/ZoneHVACComponent/ZoneHVACBaseboardConvectiveElectric.hpp>)
EPMODELOBJECT_WRAP(ZoneHVACBaseboardRadiantConvectiveWater, <epmodel/ZoneHVACComponent/ZoneHVACBaseboardRadiantConvectiveWater.hpp>)
EPMODELOBJECT_WRAP(ZoneHVACBaseboardRadiantConvectiveWaterDesign, <epmodel/ZoneHVACComponent/ZoneHVACBaseboardRadiantConvectiveWaterDesign.hpp>)
EPMODELOBJECT_WRAP(ZoneHVACCoolingPanelRadiantConvectiveWater, <epmodel/ZoneHVACComponent/ZoneHVACCoolingPanelRadiantConvectiveWater.hpp>)
EPMODELOBJECT_WRAP(ZoneHVACBaseboardRadiantConvectiveElectric, <epmodel/ZoneHVACComponent/ZoneHVACBaseboardRadiantConvectiveElectric.hpp>)
EPMODELOBJECT_WRAP(ZoneHVACBaseboardConvectiveWater, <epmodel/ZoneHVACComponent/ZoneHVACBaseboardConvectiveWater.hpp>)
EPMODELOBJECT_WRAP(WaterHeaterHeatPump, <epmodel/ZoneHVACComponent/WaterHeaterHeatPump.hpp>)
EPMODELOBJECT_WRAP(WaterHeaterHeatPumpWrappedCondenser, <epmodel/ZoneHVACComponent/WaterHeaterHeatPumpWrappedCondenser.hpp>)
EPMODELOBJECT_WRAP(ZoneHVACWaterToAirHeatPump, <epmodel/ZoneHVACComponent/ZoneHVACWaterToAirHeatPump.hpp>)
EPMODELOBJECT_WRAP(ZoneHVACDehumidifierDX, <epmodel/ZoneHVACComponent/ZoneHVACDehumidifierDX.hpp>)
EPMODELOBJECT_WRAP(ZoneHVACEnergyRecoveryVentilator, <epmodel/ZoneHVACComponent/ZoneHVACEnergyRecoveryVentilator.hpp>)
EPMODELOBJECT_WRAP(ZoneHVACEvaporativeCoolerUnit, <epmodel/ZoneHVACComponent/ZoneHVACEvaporativeCoolerUnit.hpp>)
EPMODELOBJECT_WRAP(ZoneHVACUnitHeater, <epmodel/ZoneHVACComponent/ZoneHVACUnitHeater.hpp>)
EPMODELOBJECT_WRAP(RefrigerationAirChiller, <epmodel/ZoneHVACComponent/RefrigerationAirChiller.hpp>)
EPMODELOBJECT_WRAP(ZoneVentilationWindandStackOpenArea, <epmodel/ZoneHVACComponent/ZoneVentilationWindandStackOpenArea.hpp>)
EPMODELOBJECT_WRAP(ZoneHVACUnitVentilator, <epmodel/ZoneHVACComponent/ZoneHVACUnitVentilator.hpp>)
EPMODELOBJECT_WRAP(ZoneHVACFourPipeFanCoil, <epmodel/ZoneHVACComponent/ZoneHVACFourPipeFanCoil.hpp>)
EPMODELOBJECT_WRAP(ZoneHVACHighTemperatureRadiant, <epmodel/ZoneHVACComponent/ZoneHVACHighTemperatureRadiant.hpp>)
EPMODELOBJECT_WRAP(ZoneHVACPackagedTerminalAirConditioner, <epmodel/ZoneHVACComponent/ZoneHVACPackagedTerminalAirConditioner.hpp>)
EPMODELOBJECT_WRAP(ZoneHVACPackagedTerminalHeatPump, <epmodel/ZoneHVACComponent/ZoneHVACPackagedTerminalHeatPump.hpp>)
EPMODELOBJECT_WRAP(ZoneHVACTerminalUnitVariableRefrigerantFlow, <epmodel/ZoneHVACComponent/ZoneHVACTerminalUnitVariableRefrigerantFlow.hpp>)
EPMODELOBJECT_WRAP(ZoneHVACIdealLoadsAirSystem, <epmodel/ZoneHVACComponent/ZoneHVACIdealLoadsAirSystem.hpp>)
EPMODELOBJECT_WRAP(ZoneHVACLowTempRadiantConstFlow, <epmodel/ZoneHVACComponent/ZoneHVACLowTempRadiantConstFlow.hpp>)
EPMODELOBJECT_WRAP(ZoneHVACLowTempRadiantVarFlow, <epmodel/ZoneHVACComponent/ZoneHVACLowTempRadiantVarFlow.hpp>)
EPMODELOBJECT_WRAP(ZoneHVACLowTemperatureRadiantElectric, <epmodel/ZoneHVACComponent/ZoneHVACLowTemperatureRadiantElectric.hpp>)
EPMODELOBJECT_WRAP(FanZoneExhaust, <epmodel/ZoneHVACComponent/FanZoneExhaust.hpp>)

#endif
